server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storage_buddy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: buddy_user
    password: buddy_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:Username}
  secret-key: ${MINIO_ROOT_PASSWORD:Password}
  bucket:
    name: cloud-storage-bucket
    policy:
      post-expiry-minutes: 5